name: "Java Build Action"
description: "Set up JDK, cache Maven, and build a Java project"
inputs:
  java-version:
    description: "Java version to use"
    required: true
  distribution:
    description: "JDK distribution (temurin, zulu, adopt, etc.)"
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install
      shell: bash
