name: Test JS Action

on:
  workflow_dispatch:

jobs:
  run-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom JS action
        uses: ./.github/actions/js
        with:
          name: "Namita"
